// <auto-generated />
using System;
using GuimasBurguer2026App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GuimasBurguer2026App.Data.Migrations
{
    [DbContext(typeof(HamburguerDbContext))]
    [Migration("20260528121442_AddRelacionamentoCatHamburguer")]
    partial class AddRelacionamentoCatHamburguer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.16");

            modelBuilder.Entity("CategoriaHamburguer", b =>
                {
                    b.Property<int>("CategoriasCategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HamburguersHamburguerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CategoriasCategoriaId", "HamburguersHamburguerId");

                    b.HasIndex("HamburguersHamburguerId");

                    b.ToTable("CategoriaHamburguer");
                });

            modelBuilder.Entity("GuimasBurguer2026App.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria");

                    b.HasData(
                        new
                        {
                            CategoriaId = 1,
                            Descricao = "Calórico"
                        },
                        new
                        {
                            CategoriaId = 2,
                            Descricao = "Vegano"
                        },
                        new
                        {
                            CategoriaId = 3,
                            Descricao = "Light"
                        });
                });

            modelBuilder.Entity("GuimasBurguer2026App.Models.Hamburguer", b =>
                {
                    b.Property<int>("HamburguerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("EntregaExpressa")
                        .HasColumnType("INTEGER")
                        .HasColumnName("EntregaExpressa");

                    b.Property<string>("ImagemUri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MarcaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("Preco")
                        .HasColumnType("REAL");

                    b.HasKey("HamburguerId");

                    b.ToTable("Hamburguer");
                });

            modelBuilder.Entity("GuimasBurguer2026App.Models.Marca", b =>
                {
                    b.Property<int>("MarcaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MarcaId");

                    b.ToTable("Marca");

                    b.HasData(
                        new
                        {
                            MarcaId = 1,
                            Nome = "Sadia"
                        },
                        new
                        {
                            MarcaId = 2,
                            Nome = "Seara"
                        });
                });

            modelBuilder.Entity("CategoriaHamburguer", b =>
                {
                    b.HasOne("GuimasBurguer2026App.Models.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriasCategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuimasBurguer2026App.Models.Hamburguer", null)
                        .WithMany()
                        .HasForeignKey("HamburguersHamburguerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
