// <auto-generated />
using System;
using GuimasBurguer2026App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GuimasBurguer2026App.Data.Migrations
{
    [DbContext(typeof(HamburguerDbContext))]
    partial class HamburguerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.16");

            modelBuilder.Entity("GuimasBurguer2026App.Models.Hamburguer", b =>
                {
                    b.Property<int>("HamburguerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT")
                        .HasColumnName("DataCadastro");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("EntregaExpressa")
                        .HasColumnType("INTEGER")
                        .HasColumnName("EntregaExpressa");

                    b.Property<string>("ImagemUri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MarcaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Nome");

                    b.Property<double>("Preco")
                        .HasColumnType("REAL");

                    b.HasKey("HamburguerId");

                    b.ToTable("Hamburguer");
                });

            modelBuilder.Entity("GuimasBurguer2026App.Models.Marca", b =>
                {
                    b.Property<int>("MarcaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Nome");

                    b.HasKey("MarcaId");

                    b.ToTable("Marca");

                    b.HasData(
                        new
                        {
                            MarcaId = 1,
                            Nome = "Sadia"
                        },
                        new
                        {
                            MarcaId = 2,
                            Nome = "Seara"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
